apiVersion: v1
kind: Service
metadata:
  name: {{ include "lms-app.fullname" . }}
  labels:
    {{- include "lms-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.socketioPort }}
      targetPort: socketio
      protocol: TCP
      name: socketio
  selector:
    {{- include "lms-app.selectorLabels" . | nindent 4 }}

